### ISSUE TITLE
InternalLock will cause a large amount of GC

### ISSUE THREAD

**Issue by Wolf-Warriors** [Nebukam/com.nebukam.orca#10]
Tag：1.1.8

2000Agents   -> 15.5KB GCAlloc

![Snipaste_2024-04-02_16-29-51](https://github.com/Nebukam/com.nebukam.orca/assets/18331515/58bb440d-7e38-4a81-8aa5-a0f1b3e151dc)

![Snipaste_2024-04-02_16-31-24](https://github.com/Nebukam/com.nebukam.orca/assets/18331515/80853b61-c27f-462b-9e57-8d3a6a3d89ce)

**Comment by Nebukam** [comment]
On vacation rn, will look into it when I come back. Not sure why this is generating so much garbage here -- are you changing the number of agents each frame?

**Comment by Wolf-Warriors** [comment]
您的邮件已收到！谢谢！

**Comment by Nebukam** [comment]
Hey @Wolf-Warriors! I've looked into it and can't find any GC generation on my end, unless if running the profiler in Deep mode, and even then it's not even close to your results.

**The provided examples are generating 0B of garbage, tested in Unity 2021 up to Unity 2023.**
Which version of Unity are you using?
Did you by any chance create your own Agent class with custom stuff that would explain the allocation on the list' capacity update?

The `Clear` method highlighted in step 6 is a C# object I have no control over (a basic `List`) and it's not so much clearing the list that generates garbage but setting the capacity to an updated size -- which again, if the agent' list isn't changed between updates, shouldn't generate any garbage.

If you run the Setup example, do you see the GC alloc at all?
