### ISSUE TITLE
How can I change  Agent.pos ?

### ISSUE THREAD

**Issue by chasing2moro** [Nebukam/com.nebukam.orca#4]
I change the value **pos** of **Agent**, but It does not work. Because after I do that, **Agent.pos** is assigned by **AgentData.position** immediately. So please help me： How can I change  Agent.pos ?

**Comment by Nebukam** [comment]
Hi @chasing2moro ! Thanks for reaching out :)
Since this is more a question than an issue, I opened the discussion on this github and created a thread [here ](https://github.com/Nebukam/com.nebukam.orca/discussions/5) from this issue!
See you there!

**Comment by chasing2moro** [comment]
> 

Thank you very much
