### ISSUE TITLE
Conflicts with ECS

### ISSUE THREAD

**Issue by Planktoning** [Nebukam/com.nebukam.orca#8]
When I add ORCA in a project with entities package,console shows conflicts,such as "GUID [7a96926915a7746789220056d7c409a5] for asset 'Packages/com.unity.jobs/Editor/JobsMenu.cs' conflicts with:
  'Packages/com.unity.collections/Unity.Collections.Editor/JobsMenu.cs' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored."
![1](https://github.com/Nebukam/com.nebukam.orca/assets/107417986/782ea0f1-4c15-4bcc-9bd1-a2b3f8f266a5)
:)

**Comment by Planktoning** [comment]
oh,i find the conflict, job-asstis is conflict with entities(ver 1.0.16)'s dependcy--collections.how can i reslove that？

**Comment by Nebukam** [comment]
Hello @Planktoning, what version of Unity are you using? Can you provide a little bit more details, such as the list of packages curently installed in your project?

It looks like the ECS version your version of ECS (1.0.16) is relying on a collection package that is too old (1.2.4) whereas ORCA requires **1.3.1**. 

See if you can upgrade your Collection package to 1.3.1?

**Comment by Nebukam** [comment]
Hmmm, it's not designed for ECS initially and I never worked with the DOTS architecture :(
I guess you would need some kind of identifier (a uint32 or uint64 should do) on the Agent as well as your own data class, and consolidate the data after the processing has been done.

You can implement your own agent class with ORCA, so basically just extend the `Agent` class, add a unique identifier to it, and you should be good to go!

**Comment by Planktoning** [comment]
thx！I will give it and try! :)

**Comment by ssochi** [comment]
Hi Nebukam, do you have any plans to make this library support pure ECS?

**Comment by Nebukam** [comment]
@ssochi it does support pure ECS; but using ECS for agents etc is not planned in the short term: it would require a complete rewrite of some dependencies this package relies on.

**Comment by ssochi** [comment]
Hi Nebukam,
Thank you very much for your reply. I've already implemented your RVO in my DOTS project, and it's really cool. I'm very grateful for that. However, I have a few questions I'd like to ask:

Is it possible to control the turning speed of the RVOAgent? I have many different types of units, and each type has a slightly different turning speed.
Is it possible to control the avoidance priority of the agents? In the project, we always want less important units to give way to more important units, as this would make the game look more realistic.

I'm looking forward to your reply!

**Comment by Nebukam** [comment]
Hi @ssochi !
While you can't control turning speed (this is not a concept that is part of the underlying maths), you can achieve what you describe by changing an agent' `timeHorizon`.

What this effectively does is basically how much "foresight" that agent has. High values means they consider collision long ahead of time (making them slower), while lower values gives them a "shorter sight", effectively making them generally faster and more reactive.

`timeHorizon` is used for agent/agent considerations, while `timeHorizonObst` is used for agent/obstacle considerations (these are handled separately)

Another setting you can play with is the `maxSpeed` : Agent with a high value will effectively attempt to "squeeze through" other slower agents -- think of it like allowing an agent to have small bursts of speed to get ahead of another!
