### ISSUE TITLE
when can this project support at version>=unity2022

### ISSUE THREAD

**Issue by chasingtomoro** [Nebukam/com.nebukam.orca#9]
Dear contributor，I show my appreciate to you that YOU did such an amazing ORCA project. But I found a situation that This project can only use up to unity2021. Once I upgrade to unity2022, it throw out so many compile error.

**Comment by Nebukam** [comment]
I'll need to check it out. Can you provide more infos on your setup so I can try to reproduce the issue on my end?

**Comment by chasingtomoro** [comment]
In Unity2022 force to use new Entities, other wise it will produce thousands errors. Once I upgrade Entities, Just ORCA Plugin will produce error.
![Dingtalk_20240103224309](https://github.com/Nebukam/com.nebukam.orca/assets/155503136/28e063c5-0843-4aef-a0a5-ff0f3f9065ad)

**Comment by Nebukam** [comment]
Ah yeah entities uses an old Collections packages: please update your Collection package to 1.3.1 and this should fix the problem.

**Comment by chasingtomoro** [comment]
Thx for your sincere help.

**Comment by chasingtomoro** [comment]
> Ah yeah entities uses an old Collections packages: please update your Collection package to 1.3.1 and this should fix the problem.

The Collection Version need to at least 2.1.4, So I can not solve the error by your light up path.

**Comment by Nebukam** [comment]
Hmmm ok this is tricky; I'll see what I can do on my end to ensure compatibility with recent versions of Unity. It'll require some more work on dependencies (job assist etc) so it won't be happening soon. 

In the meantime you can try to update the package locally: job-assist and ORCA both rely on the Collections but there is actually little "hard" dependency in the sense that I'm using collections along with the job system "as-is" and haven't extended the data classes themselves: there may be very little changes to do to make it work; I'll look into it as soon  as I can but don't expect a quick solve in the repo in the short term.

**Comment by chasingtomoro** [comment]
Thx for your sincere quickly reply. You are my god at this ORCA community

**Comment by Nebukam** [comment]
@chasingtomoro I submitted a fix, tested on my end with 2022.1.0f1 -- but I wasn't able to test or install entities.
Let me know if it fixes the issue on your end.

In order to test the fix you'll need to remove current ORCA packages from your project and re-sync to **com.nebukam.ORCA 1.1.5** !

**Comment by chasingtomoro** [comment]
ok.I am outdoor.I am rushing to my office to test it.I will tell you the result if the bug fixed or not. Thx again.

**Comment by Nebukam** [comment]
No problem, thanks for reporting the issues, it helps keeping this repo alive and up-to-date <3

**Comment by chasingtomoro** [comment]
It works perfectly with dependency `Collection 2.1.4`. Thank you very much. I am very happy to USE this ORCA at Unity2022 from now on.
